# Список тренировочных задач

В данном разделе курса мы представим большой список тренировочных задач по каждой из пройденных тем. Мы предлагаем вам реализовать каждую задачу как средствами библиотеки pandas, так и на SQL. Наши варианты решения задач вы сможете найти в этом же разделе в конце. Каждая задача имеет свой порядковый номер, по которому будет удобно искать соответствующий ответ.

### Map операции

#### 1.1

В таблице order_details есть поле discount_price, оно хранит данные о стоимости на позицию товара в чеке с учетом скидки, при этом в одной позиции может быть несколько товаров, следовательно, столбец discount_price содержит итоговую стоимость всех товаров в позиции. Получите новый вычислямый столбец, котором будет расчитана цена за 1 товар с учетом скидки.

#### 1.2

Создайте новый вычисляемый столбец в таблице customers, который будет хранить данные о диапазонах возрастов клиентов. Возраст расчитайте относительно даты, в которую вы решаете данную задачу. Используйте следующие рамки для расчета диапазонов:

 - 18 - 24 года
 - 25 - 34 года
 - 35 - 44 года
 - 45 - 54 года
 - 55 и более

#### 1.3

В таблице сотрудников магазина salesmen создайте два вычисляемых поля, в одном должно храниться имя сотрудника, в другом - фамилия.

#### 1.4

В таблице orders создайте новое поле, хранящее информацию о годе и номере квартала каждого заказа.

#### 1.5

В таблице order_details в новом столбце рассчитайте сумму скидки в процентах на каждую позицию товаров, результат округлите с точность до 1 знака после запятой.

#### 1.6

Создайте новый вычисляемый столбец в таблице products с классификацией товаров в зависимости от их цены. Использйте следующие диапазоны:

 - цена до 10 000 (невключительно) - класс "low price"
 - цена от 10 000 (включительно) до 100 000 (невключительно) - класс "medium price"
 - цена от 100 000 (включительно) и выше - класс "high price"

### Операции фильтрации

#### 2.1

Из таблицы orders получите такие заказы, которые были сделаны в течении 1 квартала 2023 года.

#### 2.2

Из таблицы products выведите товары, цена которых находится в диапазоне от 50 000 до 100 000.

#### 2.3

Выведите из таблицы stores список магазинов, расположенных в Москве и относящихся к классу "grand".

#### 2.4

Из таблицы order_details выведите все записи по товарам из следующего списка:

 - (1105042d-9197-4bcd-9668-bb5ab2a76221, 2487e34e-728d-4d0b-818b-45f8f111f853, b5355c21-48ad-42e7-9ee6-ebe9085881a3)

#### 2.5

Из таблицы customers выведите всех клиентов, имя которых начинается на букву А и имеет 5 и более букв в своем составе.

#### 2.6

Выведите всех клиентов, фамилии которых заканчивают на буквы "в" или "н", при этом email таких клиентов должен заканчиваться на "@gmail.com" (таблица customers).

#### 2.7

Получите список магазинов, площадь которых составляет не более 300 кв.м, при этом находящихся в одном из городов (Москва, Ульяновск, Волгоград), или же таких магазинов, класс которых является grand или mini, при этом расположенных на какой-либо аллее (в начале адреса присутствует сокращение алл.) (таблица stores).

#### 2.8

Из таблицы orders получите такие заказы, количество товаров которых находится в рамках от 2 до 5 штук, сумма чека с учетом скидки не превышает 100 000, также заказ должен быть сделан в 2022 году.

#### 2.9

Получите список сотрудников, которые были приняты на работу в последние 5 лет (относительно даты, когда вы решаете данную задачу), при этом в названии должности сотрудника должно находится слово "кассир" (таблица salesmen).

#### 2.10

Из таблицы order_details выведите данные по чекам, в которых каждая позиция содержит не менее 2 товаров, базовая стоимость позиции товара находится в пределах от 100 до 300 тысяч. Еще одним условием является то, что в позициях не должно быть товаров из данного списка: 
(
bd7e5101-71be-4935-b3e5-324636baecd6,
9088aa9a-3248-4f1a-ab3d-5527e4cd6521,
6febba3f-5ba3-428e-904f-048d9fd76897,
4864ff98-69e3-4fa5-95c9-a5d35c4cdaa5,
96e9a531-230e-4237-8011-da09df534aaa,
a720c029-0703-4120-9559-99243fe5f2b1,
fcec9f7c-1c9e-4669-87ce-a207713349e7
)

### Операции группировки, транспонирования

#### 3.1

Посчитайте общее количество, проданных товаров за все время, общую сумму выручки с учетом и без учета скидки и общее количество уникальных заказов (таблица orders).

#### 3.2

Посчитайте количество уникальных клиентов магазина (таблица customers или таблица orders).

#### 3.3

Рассчитайте продажи (суммарное количество проданных товаров), сумму выручки с учетом скидки, максимальное и минимальное количество товаров в чеке и среднюю сумму чека без учета скидки с группировкой по датам заказов (таблица orders).

#### 3.4

Рассчитайте количество сотрудников в каждой должности (таблица salesmen).

#### 3.5

Посчитайте сумму выручки и продажи с группировкой по датам и идентификаторам магазинов (таблица orders).

#### 3.6

Выведите количество товаров по каждому бренду и категории (можно использовать идентификаторы brand_id и category_id) (таблица products).

#### 3.7

Какое количество заказов сделал каждый клиент за все время? Получите также максимальную и минимальную сумму чека по каждому клиенту за всю историю заказов (таблица orders).

#### 3.8

Скольких уникальных клиентов обслужил каждый сотрудник магазина? (таблица orders).

#### 3.9

Сколько было продано в штуках каждого товара за всю историю? (таблица order_details).

### Операции join

#### 4.1

Проведите операцию внутреннего соединения между таблицами products, brands и categories.

#### 4.2

Расширьте атрибутный состав таблицы orders так, чтобы иметь доступ к адресам и классам магазинов.

#### 4.3

Получите только такие заказы для каждого клиента, которые были сделаны в его день рождения. Также можете реализовать чуть более сложный вариант данной задачи, а именно, выведите такие заказы для каждого клиента, которые были сделаны в период за 5 дней до и за 5 дней после дня рождения клиента.

#### 4.4

Получите только такие заказы, которые были сделаны в день устройства сотрудника на работу.

#### 4.5

Проведите операцию внутреннего соединения для всех таблиц нашей тренировочной модели данных.

#### 4.6

Получите список клиентов, у которых день рождения (день и месяц) совпадает с днем и месяцем устройства на работу хотя бы 1 сотрудника из штата магазинов.

#### 4.7

### Операции конкатенации

#### 5.1

Используя операцию со множествами, проверьте, есть ли такие клиенты, которые ни разу не делали никаких заказов за всю историю.

#### 5.2

С помощью операции со множествами получите список имен и фамилий клиентов и сотрудников, исключив при этом дублирующиеся записи.

#### 5.3

Через операцию со множествами получите список имен и фамилий, которые совпадают у клиентов и сотрудников сети.

### Операции сортировки

#### 6.1

Получите таблицу со списком клиентов, отсортированную по дате рождения по возрастанию

#### 6.2

Получите таблицу со списком сотрудников, отсортировав данные по дате устройства на работу по возрастанию и по имени и фамилии по убыванию.

#### 6.3

Выведите данные из таблицы products, отсортировав их по цене и названию товара по убыванию.

### Оконные функции, накопительный итог

#### 7.1

В таблице products создайте новый столбец, показывающий в каждой строке общее количество уникальных товаров, продающихся в сети магазинов.

#### 7.2

В таблице products напротив каждого бренда проставьте среднюю цену составляющих его товаров, гранулярность таблицы products не должна измениться.

#### 7.3

Теперь добавьте разбивку также по категории, иными словами, рассчитайте среднюю цену товаров, входящих в каждый бренд каждой категории. Гранулярность таблицы products не должна измениться.

#### 7.4

В таблице orders напротив каждого клиента получите общее количество его заказов за всю историю, при этом гранулярность таблицы не должна измениться.

#### 7.5

По каждому сотруднику магазинов в таблице orders рассчитайте максимальную сумму чека с учетом скидки среди когда-либо оформленных заказов, гранулярность таблицы orders не должна измениться.

#### 7.6

По каждому клиенту в таблице orders расчитайте накопительную сумму по его заказам (с учетом скидки), отсортировав даты покупок по возрастанию.

#### 7.7

В таблице stores проранжируйте магазины в зависимости от их площади. Самый большой по площади магазин должен получить ранг 1, если площадь у магазинов совпадает, то они должны получить одинаковые ранги, а последующие магазины ранг по порядку (без перескакивания).

#### 7.8

В таблице orders проранжируйте заказы для каждого клиента, отсортировав покупки по возрастанию даты. Иными словами, первый заказ должен получить ранг 1, если даты заказов совпадут, тогда высший ранг (с меньшим по модулю числом) должен получить заказ с большей суммой чека.

#### 7.9

Для каждого клиента в таблице orders получите дату его предыдущего и последующего заказа.

### Общий список задач